# Generated by Django 3.1.1 on 2020-10-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=250),
        ),
    ]
